name: dola-nlp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - matplotlib
  - numpy
  - tqdm
  - pyyaml
  - pytorch>=2.1
  - pytorch-cuda=11.8
  - pip:
      - transformers>=4.38
      - datasets>=2.18
      - accelerate>=0.27
      - sentencepiece>=0.2
      - protobuf>=4.25
